package ljl.dao;

import ljl.entity.TSc;
import ljl.entity.TScKey;

public interface TScMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SC
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TScKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SC
     *
     * @mbg.generated
     */
    int insert(TSc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SC
     *
     * @mbg.generated
     */
    int insertSelective(TSc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SC
     *
     * @mbg.generated
     */
    TSc selectByPrimaryKey(TScKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SC
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SC
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSc record);
}