package ljl.dao;

import ljl.entity.TStudent;

public interface TStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated
     */
    int insert(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated
     */
    int insertSelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated
     */
    TStudent selectByPrimaryKey(Long stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TStudent record);
}