package com.vjsp.dao;

import com.vjsp.entity.Bonus;

public interface BonusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BONUS
     *
     * @mbg.generated
     */
    int insert(Bonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BONUS
     *
     * @mbg.generated
     */
    int insertSelective(Bonus record);
}