package com.vjsp.dao;

import com.vjsp.domain.City;
import com.vjsp.domain.CityKey;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(CityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbg.generated
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbg.generated
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbg.generated
     */
    City selectByPrimaryKey(CityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(City record);
}