package com.vjsp.dao;

import com.vjsp.entity.Salgrade;

public interface SalgradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALGRADE
     *
     * @mbg.generated
     */
    int insert(Salgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALGRADE
     *
     * @mbg.generated
     */
    int insertSelective(Salgrade record);
}