package ljl.entity;

public class TCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COURSE.CID
     *
     * @mbg.generated
     */
    private Long cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COURSE.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COURSE.TEACHERID
     *
     * @mbg.generated
     */
    private Long teacherid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COURSE.CID
     *
     * @return the value of T_COURSE.CID
     *
     * @mbg.generated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COURSE.CID
     *
     * @param cid the value for T_COURSE.CID
     *
     * @mbg.generated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COURSE.NAME
     *
     * @return the value of T_COURSE.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COURSE.NAME
     *
     * @param name the value for T_COURSE.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COURSE.TEACHERID
     *
     * @return the value of T_COURSE.TEACHERID
     *
     * @mbg.generated
     */
    public Long getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COURSE.TEACHERID
     *
     * @param teacherid the value for T_COURSE.TEACHERID
     *
     * @mbg.generated
     */
    public void setTeacherid(Long teacherid) {
        this.teacherid = teacherid;
    }
}