package ljl.entity;

public class TSc extends TScKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SC.SCORE
     *
     * @mbg.generated
     */
    private Long score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SC.SCORE
     *
     * @return the value of T_SC.SCORE
     *
     * @mbg.generated
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SC.SCORE
     *
     * @param score the value for T_SC.SCORE
     *
     * @mbg.generated
     */
    public void setScore(Long score) {
        this.score = score;
    }
}