package ljl.entity;

public class TScKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SC.STUID
     *
     * @mbg.generated
     */
    private Long stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SC.CID
     *
     * @mbg.generated
     */
    private Long cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SC.STUID
     *
     * @return the value of T_SC.STUID
     *
     * @mbg.generated
     */
    public Long getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SC.STUID
     *
     * @param stuid the value for T_SC.STUID
     *
     * @mbg.generated
     */
    public void setStuid(Long stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SC.CID
     *
     * @return the value of T_SC.CID
     *
     * @mbg.generated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SC.CID
     *
     * @param cid the value for T_SC.CID
     *
     * @mbg.generated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }
}