package ljl.entity;

public class TStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STUDENT.STUID
     *
     * @mbg.generated
     */
    private Long stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STUDENT.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STUDENT.AGE
     *
     * @mbg.generated
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STUDENT.SEX
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STUDENT.STUID
     *
     * @return the value of T_STUDENT.STUID
     *
     * @mbg.generated
     */
    public Long getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STUDENT.STUID
     *
     * @param stuid the value for T_STUDENT.STUID
     *
     * @mbg.generated
     */
    public void setStuid(Long stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STUDENT.NAME
     *
     * @return the value of T_STUDENT.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STUDENT.NAME
     *
     * @param name the value for T_STUDENT.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STUDENT.AGE
     *
     * @return the value of T_STUDENT.AGE
     *
     * @mbg.generated
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STUDENT.AGE
     *
     * @param age the value for T_STUDENT.AGE
     *
     * @mbg.generated
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STUDENT.SEX
     *
     * @return the value of T_STUDENT.SEX
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STUDENT.SEX
     *
     * @param sex the value for T_STUDENT.SEX
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
}