package ljl.entity;

public class TTeacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEACHER.TID
     *
     * @mbg.generated
     */
    private Long tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEACHER.TNAME
     *
     * @mbg.generated
     */
    private String tname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEACHER.TID
     *
     * @return the value of T_TEACHER.TID
     *
     * @mbg.generated
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEACHER.TID
     *
     * @param tid the value for T_TEACHER.TID
     *
     * @mbg.generated
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEACHER.TNAME
     *
     * @return the value of T_TEACHER.TNAME
     *
     * @mbg.generated
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEACHER.TNAME
     *
     * @param tname the value for T_TEACHER.TNAME
     *
     * @mbg.generated
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }
}