package ljl.tem;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by Administrator on 2017/5/2.
 */
public class C {
   static String s1="PLCA_ACCUM_TRANSFORM_RULE,\n" +
            "PLCA_ACTION,\n" +
            "PLCA_CONDITION,\n" +
            "PLCA_EVENT_TYPE,\n" +
            "PLCA_OPERATOR,\n" +
            "PLCA_REF_VALUE,\n" +
            "PLCA_REF_VALUE_SET,\n" +
            "PLCA_SECTION,\n" +
            "PLCA_SECTION_ACTION_REL,\n" +
            "PLCA_STRATEGY,\n" +
            "PLCA_STRATEGY_GROUP,\n" +
            "PLCA_STRATEGY_OBJECT,\n" +
            "PLCA_TIME_PERIOD_DEFINE,\n" +
            "POLITICAL_LOCATION,\n" +
            "POSITION,\n" +
            "PRICING_COMBINE,\n" +
            "PRICING_COMBINE_REL,\n" +
            "PRICING_ENUM_PARAM,\n" +
            "PRICING_OBJECT,\n" +
            "PRICING_PARAM_DEFINE,\n" +
            "PRICING_PLAN,\n" +
            "PRICING_PLAN_REL,\n" +
            "PRICING_REF_OBJECT,\n" +
            "PRICING_REF_VALUE,\n" +
            "PRICING_RULE,\n" +
            "PRICING_SECTION,\n" +
            "PRICING_SECTION_REL,\n" +
            "PRICING_SECTION_TYPE,\n" +
            "PRIVILEGE,\n" +
            "PRIV_DATA_REL,\n" +
            "PRIV_FUNC_REL,\n" +
            "PRIV_GRANT,\n" +
            "PRODUCT,\n" +
            "PRODUCT_PROVIDER,\n" +
            "PRODUCT_USAGE_EVENT_TYPE,\n" +
            "PROD_ACCT_ITEM_TYPE_REL,\n" +
            "PROD_ATTR,\n" +
            "PROD_ATTR_VALUE,\n" +
            "PROD_ATTR_VALUE_RESTRICT,\n" +
            "PROD_CATALOG_LOCATION,\n" +
            "PROD_INST,\n" +
            "PROD_INST_ACC_NBR_ATTR,\n" +
            "PROD_INST_ACC_NBR_REL,\n" +
            "PROD_INST_ACC_NUM,\n" +
            "PROD_INST_ASSIGN_REL,\n" +
            "PROD_INST_ATTR,\n" +
            "PROD_INST_ATTR_REL,\n" +
            "PROD_INST_CONTACT,\n" +
            "PROD_INST_HIS,\n" +
            "PROD_INST_REL,\n" +
            "PROD_INST_REL_ROLE,\n" +
            "PROD_INST_STATE,\n" +
            "PROD_NUM_TYPE_PLAT_REL,\n" +
            "PROD_NUM_TYPE_REL,\n" +
            "PROD_OFFER_BALANCE_REL,\n" +
            "PROD_OFFER_INST_PARTY,\n" +
            "PROD_OFFER_INST_REL_ROLE,\n" +
            "PROD_PARTNER_REL,\n" +
            "PROD_REGION_REL,\n" +
            "PROD_REL,\n" +
            "PROD_REL_EFF_EXP_CFG,\n" +
            "PROD_REL_ROLE,\n" +
            "PROD_REL_RSTR_CFG,\n" +
            "PROD_REL_SERV_LINK_RUL,\n" +
            "PROD_RES_INST_REL,\n" +
            "PROD_RES_REL,\n" +
            "PROD_SERVICE_OFFER_REL,\n" +
            "PROD_SERV_REL_RSTR_CFG,\n" +
            "PROD_STATUS_SERV_RSTR_CFG,\n" +
            "PROMOTIONAL_ACTIVITY,\n" +
            "PROMOTIONAL_ACTIVITY_RELA,\n" +
            "PROMOTIONAL_ACTIVITY_TARIFF,\n" +
            "PROMOTIONAL_ACT_TARIFF_RULE,\n" +
            "PROM_ACTI_MTK_RELA,\n" +
            "PROM_ACTI_TARIFF_RELA,\n" +
            "RATABLE_CYCLE,\n" +
            "RATABLE_CYCLE_TYPE,\n" +
            "RATABLE_RESOURCE_ACCUMULATOR,\n" +
            "REASON_TYPE,\n" +
            "REBATE,\n" +
            "RECEIPT_TAX_INVOICE,\n" +
            "REFUND_DETAIL,\n" +
            "REFUND_DETAIL_ITEM,\n" +
            "REGION_GRID_RELATION,\n" +
            "REGION_LOCATION_REL,\n" +
            "REL_SERV_LINK_RUL,\n" +
            "REL_SPEC,\n" +
            "REL_SPEC_ATTR,\n" +
            "REPAIR_RANGE,\n" +
            "REWARD_ADJ_INFO,\n" +
            "REWARD_APRV_INFO,\n" +
            "REWARD_INFO,\n" +
            "REWARD_PAY_INFO,\n" +
            "ROUTE_INFO,\n" +
            "SALE_ACCOUNT,\n" +
            "SALE_CUST,\n" +
            "SALE_HANDLER,\n" +
            "SALE_ITEM,\n" +
            "SALE_MKT_RES_INST,\n" +
            "SALE_OFFER_INST,\n" +
            "SALE_ORDER,\n" +
            "SALE_ORDER_ITEM_ATTR,\n" +
            "SALE_PROD_INST,\n" +
            "SERVICE_ABILITY,\n" +
            "SERVICE_GRADE,\n" +
            "SERVICE_GRADE_LOG,\n" +
            "SERVICE_OFFER,\n" +
            "SERVICE_REQMT_GEN,\n" +
            "SERVICE_REQMT_IND,\n" +
            "SERV_ACCT_REL,\n" +
            "SERV_ACCT_REL_ATTR,\n" +
            "SERV_ACCU_USE_INFO,\n" +
            "SERV_AUTH,\n" +
            "SERV_RSTR_RUL,\n" +
            "SETTLE_RESULT_DETAIL_INFO,\n" +
            "SETTLE_RESULT_INFO,\n" +
            "SHOPPING_CART,\n" +
            "SHOPPING_CART_ITEM,\n" +
            "SOURCE_EVENT,\n" +
            "SOURCE_EVENT_FORMAT,\n" +
            "SOURCE_EVENT_FORMAT_ITEM,\n" +
            "SOURCE_EVENT_FORMAT_NORMAL,\n" +
            "SOURCE_EVENT_FORMAT_OTHER,\n" +
            "SOURCE_EVENT_FORMAT_SEGMENT,\n" +
            "SOURCE_EVENT_TYPE,\n" +
            "SPECIAL_HEAD,\n" +
            "SPECIAL_LIST,\n" +
            "SPECIAL_REQMT_GEN,\n" +
            "SPECIAL_REQMT_IND,\n" +
            "STAFF,\n" +
            "STAFF_ATTR,\n" +
            "STAFF_CHANNEL_RELA,\n" +
            "STAFF_CONTACT_INFO,\n" +
            "STAFF_OPERATORS_RELA,\n" +
            "STAFF_ORG_REL,\n" +
            "STAFF_POST,\n" +
            "SYSTEM_POST,\n" +
            "SYSTEM_POST_ROLE,\n" +
            "SYSTEM_ROLES,\n" +
            "SYSTEM_USER,\n" +
            "SYSTEM_USER_ATTR,\n" +
            "SYSTEM_USER_POST,\n" +
            "SYSTEM_USER_ROLE,\n" +
            "SYSUSER_COLLECTION,\n" +
            "SYSUSER_LOGIN_LIMIT,\n" +
            "SYS_COLUMN,\n" +
            "SYS_DOMAIN,\n" +
            "SYS_TABLE,\n" +
            "TARIFF,\n" +
            "TARIFF_CALC_DESC,\n" +
            "TARIFF_UNIT,\n" +
            "TAX_INVOICE_FEE,\n" +
            "TAX_ITEM,\n" +
            "TAX_PAYER,\n" +
            "TAX_PAYER_ATTR,\n" +
            "TAX_RATE_CONFIG,\n" +
            "TEMP_CREDIT_LIMIT,\n" +
            "THIRD_PARTY_CHN_INFO,\n" +
            "TIME_SEGMENT,\n" +
            "TRADE_RECORD,\n" +
            "TRADE_TYPE,\n" +
            "TRAFFIC_IDENTIFY,\n" +
            "TRAFFIC_IDENTIFY_OBJ_REL,\n" +
            "TRAFFIC_IDENTIFY_RULE,\n" +
            "TRAFFIC_IDENTIFY_RULE_ATTR,\n" +
            "TRAFFIC_IDENTIFY_RULE_ATTR_VAL,\n" +
            "TRAFFIC_IDENTIFY_RULE_REL,\n" +
            "UNITE_CHARGE_LOG,\n" +
            "USER_INTEGRAL_RESULT,\n" +
            "VALUE_ADDED_PROD,\n" +
            "VALUE_ADDED_PROD_CONTENT_REL,\n" +
            "VALUE_ADDED_PROD_INFO,\n" +
            "VAT_INVOICE,\n" +
            "VAT_INVOICE_DETAIL,\n" +
            "VAT_INVOICE_DETAIL_PRN,\n" +
            "VAT_INVOICE_PRN,\n" +
            "VA_ADDED_PROD_SERV_ABILITY_REL,\n" +
            "VA_OFFER,\n" +
            "VA_OFFER_EFF_EXP_CONFIG,\n" +
            "VA_OFFER_PRICE,\n" +
            "VA_OFFER_PROD_REL,\n" +
            "VA_OFFER_PROD_REL_ROLE,\n" +
            "VA_ORDER_REL,\n" +
            "VA_ORDER_REL_ATTR,\n" +
            "VA_PROD_ATTR,\n" +
            "VA_PROD_PLAT_REL,\n" +
            "VA_PROD_REL,\n" +
            "ZONE,\n" +
            "ZONE_ITEM,\n" +
            "ZONE_ITEM_VALUE,\n" +
            "MKT_RES_EVENT,\n" +
            "MKT_RES_EXTTYPE,\n" +
            "MKT_RES_EXTTYPE_ATTR,\n" +
            "MKT_RES_EXTTYPE_ATTR_VALUE,\n" +
            "MKT_RES_EXT_ATTR,\n" +
            "MKT_RES_GRP,\n" +
            "MKT_RES_GRP_RES_REL,\n" +
            "MKT_RES_INST,\n" +
            "MKT_RES_INST_ATTR,\n" +
            "MKT_RES_INST_STORE,\n" +
            "MKT_RES_INVENTORY_DETAIL,\n" +
            "MKT_RES_INV_ERR_REC,\n" +
            "MKT_RES_INV_EVENT,\n" +
            "MKT_RES_INV_EVT_DETAIL,\n" +
            "MKT_RES_INV_INST,\n" +
            "MKT_RES_INV_INST_ATTR,\n" +
            "MKT_RES_INV_USE_REC,\n" +
            "MKT_RES_NUM_EVENT,\n" +
            "MKT_RES_NUM_EVT_DETAIL,\n" +
            "MKT_RES_NUM_FMT_CFG,\n" +
            "MKT_RES_NUM_INST,\n" +
            "MKT_RES_NUM_PRE_USE,\n" +
            "MKT_RES_NUM_USE_REC,\n" +
            "MKT_RES_REGION,\n" +
            "MKT_RES_REQUEST,\n" +
            "MKT_RES_REQ_ATTR,\n" +
            "MKT_RES_REQ_DETAIL,\n" +
            "MKT_RES_REQ_ITEM,\n" +
            "MKT_RES_REQ_ITEM_ATTR,\n" +
            "MKT_RES_STOCK_ALARM,\n" +
            "MKT_RES_STORE,\n" +
            "MKT_RES_STORE_ATTR,\n" +
            "MKT_RES_STORE_ORG_REL,\n" +
            "MKT_RES_STORE_REL,\n" +
            "MKT_RES_TYPE,\n" +
            "MKT_RES_TYPE_ATTR,\n" +
            "MKT_RES_TYPE_ATTR_VALUE,\n" +
            "MKT_RES_TYPE_REGION,\n" +
            "MKT_RES_USE_REC,\n" +
            "MKT_TERMINAL_REPAIR_STATION,\n" +
            "MTK_ACCT_ITEM,\n" +
            "MTK_ORD_INFO,\n" +
            "MTK_ORD_PAY_INFO,\n" +
            "MTK_PRICING_ARRAY,\n" +
            "MTK_PRICING_ATTR,\n" +
            "MTK_PRICING_ENUM_PARAM,\n" +
            "MTK_PRICING_PLAN,\n" +
            "MTK_TAX_RATE_CONFIG,\n" +
            "NUM_GENER_RUL,\n" +
            "OBJECT_LABEL_REL,\n" +
            "OBJ_ATTR_RSTR_RUL,\n" +
            "OBJ_ATTR_RSTR_RUL_TEMPLET,\n" +
            "OBJ_ATTR_RUL,\n" +
            "OBJ_ATTR_VALUE_RSTR_RUL,\n" +
            "OBJ_CAT_ITEM_REL,\n" +
            "OBJ_COUNT_LIMIT_RUL,\n" +
            "OBJ_DOC_REL,\n" +
            "OBJ_REGION_REL,\n" +
            "OBJ_TAB_REL,\n" +
            "OCS_RESERVE_EVENT_GRP,\n" +
            "OCS_RESERVE_EVENT_GRP_MEMBER,\n" +
            "OCS_RESERVE_LIMIT,\n" +
            "OCS_RESERVE_POLICY,\n" +
            "OFFER,\n" +
            "OFFER_AGREE,\n" +
            "OFFER_AGREE_ATTR,\n" +
            "OFFER_AGREE_FEE,\n" +
            "OFFER_AGREE_OBJ,\n" +
            "OFFER_APPLY_TARGET_CFG,\n" +
            "OFFER_ASSURE_DEMAND,\n" +
            "OFFER_ATTR,\n" +
            "OFFER_ATTR_REF,\n" +
            "OFFER_ATTR_RULE,\n" +
            "OFFER_ATTR_VALUE,\n" +
            "OFFER_COMP_EFF_EXP_CFG,\n" +
            "OFFER_COMP_REL_RSTR_CFG,\n" +
            "OFFER_COMP_RSTR_CFG,\n" +
            "OFFER_EFF_EXP_CONFIG,\n" +
            "OFFER_EXP_CFG,\n" +
            "OFFER_EXP_DETAIL_ATTR_CFG,\n" +
            "OFFER_EXP_DETAIL_CFG,\n" +
            "OFFER_EXT_ATTR,\n" +
            "OFFER_GRP,\n" +
            "OFFER_GRP_MEMBER,\n" +
            "OFFER_GRP_RELA,\n" +
            "OFFER_INST,\n" +
            "OFFER_INST_ASSURE,\n" +
            "OFFER_INST_ASSURE_ATTR,\n" +
            "OFFER_INST_ATTR,\n" +
            "OFFER_INST_FEE_ATTR,\n" +
            "OFFER_INST_FEE_INFO,\n" +
            "OFFER_INST_REL,\n" +
            "OFFER_OBJ_INST_REL,\n" +
            "OFFER_OBJ_INST_REL_ROLE,\n" +
            "OFFER_OBJ_REL,\n" +
            "OFFER_OBJ_REL_ROLE,\n" +
            "OFFER_PACKAGE,\n" +
            "OFFER_PACKAGE_RESTRICT,\n" +
            "OFFER_PAYMENT_MODE,\n" +
            "OFFER_PKG_ATTR,\n" +
            "OFFER_PKG_ATTR_VALUE,\n" +
            "OFFER_PROD_ATTR_REL_CFG,\n" +
            "OFFER_PROD_INST_REL,\n" +
            "OFFER_PROD_REL,\n" +
            "OFFER_PROD_REL_RSTR_CFG,\n" +
            "OFFER_REL,\n" +
            "OFFER_REL_ROLE,\n" +
            "OFFER_REL_RSTR_CFG,\n" +
            "OFFER_RESTRICT,\n" +
            "OFFER_RES_INST_REL,\n" +
            "OFFER_RES_REL,\n" +
            "OFFER_RSTR_CFG,\n" +
            "OFFER_RSTR_GRP,\n" +
            "OFFER_RSTR_RUL,\n" +
            "OFFER_SALE_LIMIT_CFG,\n" +
            "OFFER_SERVICE_REL,\n" +
            "OFFER_SERV_LIMIT_CFG,\n" +
            "OFFER_SERV_PRIV_CFG,\n" +
            "ONE_ITEM_DISCOUNT_LOG,\n" +
            "ONE_ITEM_RESULT,\n" +
            "OPERATOR,\n" +
            "OPERATORS,\n" +
            "OPERATORS_ATTR,\n" +
            "OPERATORS_CONTACT_INFO,\n" +
            "ORDER_ATTR,\n" +
            "ORDER_BALANCE,\n" +
            "ORDER_CONTACT_INFO,\n" +
            "ORDER_HANDLER,\n" +
            "ORDER_ITEM,\n" +
            "ORDER_MODIFY,\n" +
            "ORDER_SPLIT_RUL,\n" +
            "ORDER_SRC,\n" +
            "ORD_ACCOUNT,\n" +
            "ORD_ACC_NBR_ATTR,\n" +
            "ORD_BILL_FORMAT_CUSTOMIZE_DTL,\n" +
            "ORD_CERT_INFO,\n" +
            "ORD_COMM_ACCT,\n" +
            "ORD_CONN_ACCOUNT,\n" +
            "ORD_CONTACTS_INFO,\n" +
            "ORD_CREDIT,\n" +
            "ORD_CUSTOMER,\n" +
            "ORD_DEV_STAFF_INFO,\n" +
            "ORD_EXT_ACCT,\n" +
            "ORD_GROUP_PAY_LIMIT,\n" +
            "ORD_MKT_RES_INST,\n" +
            "ORD_OFFER_INST,\n" +
            "ORD_PARTY,\n" +
            "ORD_PAY_TRANS_INST_DETAIL,\n" +
            "ORD_PROD_INST,\n" +
            "ORD_ROUTE_INFO,\n" +
            "ORD_SERVICE_GRADE,\n" +
            "ORD_SPECIAL_LIST,\n" +
            "ORD_TAX_PAYER,\n" +
            "ORD_TEMP_CREDIT_LIMIT,\n" +
            "ORGANIZATION,\n" +
            "ORG_ATTR,\n" +
            "ORG_POST_REL,\n" +
            "ORG_REL,\n" +
            "OWNER,\n" +
            "PACKAGE_OBJ_REL,\n" +
            "PARAM_CONFIG,\n" +
            "PARTNER,\n" +
            "PARTNER_ABNORMAL,\n" +
            "PARTNER_ACCOUNT,\n" +
            "PARTNER_ACCT_ITEM,\n" +
            "PARTNER_ATTRIBUTE,\n" +
            "PARTNER_COMPLAIN_INFO,\n" +
            "PARTNER_DOCUMENT,\n" +
            "PARTNER_EVAL_ADJ,\n" +
            "PARTNER_EVAL_ASSESS_INFO,\n" +
            "PARTNER_STATUS_CHNG_REC,\n" +
            "PARTY,\n" +
            "PARTY_ATTR,\n" +
            "PARTY_CERT,\n" +
            "PARTY_CHECK_LOG,\n" +
            "PARTY_IND,\n" +
            "PARTY_ORG,\n" +
            "PARTY_REL,\n" +
            "PARTY_ROLE,\n" +
            "PAYMENT_METHOD,\n" +
            "PAYMENT_RSTR_RUL,\n" +
            "PAYMENT_RULE,\n" +
            "PAY_NOTICE,\n" +
            "PAY_STRATEGY,\n" +
            "PAY_TRANS_INST_DETAIL,\n" +
            "PLAT_INFO,\n" +
            "PLCA_ACCUM_EXPRESS,\n" +
            "PLCA_ACCUM_TRANSFORM_LIMIT,\n" +
            "CHANNEL_ATTR,\n" +
            "CHANNEL_ATTRIBUTE,\n" +
            "CHANNEL_AUTHORIZATION,\n" +
            "CHANNEL_CHG_INFO,\n" +
            "CHANNEL_CONTRACT,\n" +
            "CHANNEL_CPN_INFO,\n" +
            "CHANNEL_CPN_WORKSHEET,\n" +
            "CHANNEL_KPI,\n" +
            "CHANNEL_MEMBER,\n" +
            "CHANNEL_MEMBER_ATTRIBUTE,\n" +
            "CHANNEL_OPERATORS_RELA,\n" +
            "CHANNEL_RELA,\n" +
            "CHANNEL_RESOURCE,\n" +
            "CHANNEL_TEAM,\n" +
            "CHANNEL_TRAIN_INFO,\n" +
            "CHECK_REQUEST_INFO,\n" +
            "CHN_ABNL_INFO,\n" +
            "CHN_ACC_AMT_ADJ_INFO,\n" +
            "CHN_ACC_AMT_CHG_INFO,\n" +
            "CHN_ACC_ATTR,\n" +
            "CHN_ASSESS_ADJ_REC,\n" +
            "CHN_ASSESS_REC,\n" +
            "CHN_AUTH_OBJ,\n" +
            "CHN_CONTRACT_CHG,\n" +
            "CHN_CORR_INTER_MODE,\n" +
            "CHN_CORR_ORG_UNIT,\n" +
            "CHN_EVAL_REC,\n" +
            "CHN_MEM_TRAIN,\n" +
            "CHN_ORG_UNIT,\n" +
            "CHN_ORG_UNIT_CORR_MEM,\n" +
            "CHN_ORG_UNIT_REL,\n" +
            "CHN_RES_APPL,\n" +
            "CLUB,\n" +
            "CLUB_MEMBER,\n" +
            "CLUB_MEMBER_ACTION,\n" +
            "CLUB_MEMBER_LEV_SERVICE_REL,\n" +
            "CLUB_MEMBER_SERVICE,\n" +
            "COMM_ACCT,\n" +
            "CONN_ACCOUNT,\n" +
            "CONTACTS_INFO,\n" +
            "CONTACTS_INFO_ATTR,\n" +
            "CONTENT,\n" +
            "CONTENT_ATTR,\n" +
            "COUNT_LIMIT_COMP_MBR,\n" +
            "COUPON,\n" +
            "COUPON_INST,\n" +
            "CREDIT,\n" +
            "CREDIT_LIMIT,\n" +
            "CREDIT_LIMIT_LOG,\n" +
            "CREDIT_LOG,\n" +
            "CREDIT_RSTR_RUL,\n" +
            "CREDIT_RUL,\n" +
            "CUSTOMER_ORDER,\n" +
            "CUST_ASSIGN_REL,\n" +
            "CUST_ATTR,\n" +
            "CUST_BRAND,\n" +
            "CUST_BRAND_HIS,\n" +
            "CUST_CONTACT_INFO_REL,\n" +
            "CUST_GROUP,\n" +
            "CUST_GROUP_FEATURE,\n" +
            "CUST_GROUP_FEATURE_DETAIL,\n" +
            "CUST_GROUP_MEMBER,\n" +
            "CUST_GROUP_REL,\n" +
            "CUST_INDUSTRY_TYPE,\n" +
            "CUST_KEY_INDUSTRY_REL,\n" +
            "CUST_KEY_PERSON_REL,\n" +
            "CUST_PROD_INST_REL,\n" +
            "CUST_TREE,\n" +
            "CUST_TREE_NODE,\n" +
            "DATA_FORMAT,\n" +
            "DATA_PRIV_RULE,\n" +
            "DECISION_CHAIN,\n" +
            "DECISION_CHAIN_LOG,\n" +
            "DECISION_CHAIN_ROLE,\n" +
            "DECISION_CHAIN_ROLE_RELA,\n" +
            "DEDUCTION,\n" +
            "DEPOSIT,\n" +
            "DEPOSIT_PAY_RULE,\n" +
            "DEPOSIT_TRADE_DETAIL,\n" +
            "DEPOSIT_TRADE_DETAIL_ATTR,\n" +
            "DEPOSIT_TYPE,\n" +
            "DEST_EVENT_FORMAT,\n" +
            "DEST_EVENT_FORMAT_ITEM,\n" +
            "DEST_EVENT_TYPE,\n" +
            "DEV_STAFF_INFO,\n" +
            "DF_OFFER_GIFT_SET,\n" +
            "DISCOUNT_CALC,\n" +
            "DISCOUNT_CALC_METHOD,\n" +
            "DISCOUNT_CALC_OBJECT,\n" +
            "DISCOUNT_REPATITION_TYPE,\n" +
            "DISCOUNT_TARGET_OBJECT,\n" +
            "DISCOUNT_TIME_LIMIT,\n" +
            "DOCUMENT,\n" +
            "DOC_CONTENT,\n" +
            "EMULATORY_PARTNER,\n" +
            "EQUIP,\n" +
            "EQUIP_REGION,\n" +
            "EQUIP_TYPE,\n" +
            "EVENT_ATTR,\n" +
            "EVENT_CONTENT,\n" +
            "EVENT_CONTENT_INDEX,\n" +
            "EVENT_PRICING_STRATEGY,\n" +
            "EXCH,\n" +
            "EXCH_NUM_REL,\n" +
            "EXPRESS,\n" +
            "EXPRESS_TEMPLATE,\n" +
            "EXPRESS_TEMPLATE_PARAM,\n" +
            "EXT_ACCT,\n" +
            "FIXED_PRICE,\n" +
            "FORMAT_SCRIPT,\n" +
            "FUNC_COMP,\n" +
            "FUNC_MENU,\n" +
            "GRID,\n" +
            "GRID_ASSIGN_REL,\n" +
            "GRID_ATTRIBUTE,\n" +
            "GRID_CUST_RELA,\n" +
            "GRID_GRID_UNIT_RELA,\n" +
            "GRID_PROD_RELA,\n" +
            "GRID_UNIT,\n" +
            "GRID_UNIT_ATTRIBUTE,\n" +
            "GRID_UNIT_PROD_RELA,\n" +
            "GROUP_PAY_LIMIT,\n" +
            "GROUP_PAY_TRANS_INST,\n" +
            "GROUP_PURCHASE,\n" +
            "HANDWORK_ACCT_ITEM,\n" +
            "HANDWORK_ACCT_ITEM_DETAIL,\n" +
            "HCODE,\n" +
            "INTEGRAL_BALANCE_PAYOUT,\n" +
            "INTEGRAL_BALANCE_SOURCE,\n" +
            "INTEGRAL_CALC_RULE,\n" +
            "INTEGRAL_CALC_RULE_REL,\n" +
            "INTEGRAL_CONDITION,\n" +
            "INTEGRAL_EVENT_TYPE,\n" +
            "INTEGRAL_EXCH_DETAIL,\n" +
            "INTEGRAL_FACTOR,\n" +
            "INTEGRAL_TARIFF,\n" +
            "INTEGRAL_TYPE,\n" +
            "INTERACTION_MODE,\n" +
            "INTERVIEW_LOG,\n" +
            "INTERVIEW_PLAN,\n" +
            "INTERVIEW_PLAN_ATTACH,\n" +
            "INTF_UNITEPAY_OPERATION_LOG,\n" +
            "INVOICE,\n" +
            "INVOICE_TYPE,\n" +
            "INV_CANCEL,\n" +
            "INV_DETAIL,\n" +
            "INV_ISSUED_AD_DETAIL,\n" +
            "INV_ISSUED_DETAIL,\n" +
            "INV_ISSUED_REC,\n" +
            "INV_PRINT_LOG,\n" +
            "KEY_PERSON,\n" +
            "KEY_PERSON_ATTR,\n" +
            "KEY_PERSON_REL,\n" +
            "LABEL,\n" +
            "LABEL_GROUP,\n" +
            "LABEL_GROUP_REL,\n" +
            "LATE_FEE_ADJUST,\n" +
            "LATE_FEE_ADJUSTED_REASON,\n" +
            "LATE_FEE_COMPUTE_RULE,\n" +
            "LATE_FEE_RATE,\n" +
            "LIFE_CYCLE,\n" +
            "LOCAL_HEAD,\n" +
            "LOCAL_HLR,\n" +
            "MEASURE_METHOD,\n" +
            "MEMBER_ACTION_RECORD,\n" +
            "MEMBER_ASSESS_RECORD,\n" +
            "MEMBER_CARD_GRANT_RECORD,\n" +
            "MEMBER_CHANGE_RECORD,\n" +
            "MEMBER_EXTENDED_ATTRIBUTE,\n" +
            "MEMBER_SERVICE_CATALOG_LOC,\n" +
            "MEMBER_SERVICE_RECORD,\n" +
            "MEM_SERV_ACCT,\n" +
            "MIN_NBR,\n" +
            "MIN_NUM_REL,\n" +
            "MIN_SECTION,\n" +
            "MKT_RESOURCE,\n" +
            "MKT_RES_ATTR,\n" +
            "MKT_RES_ATTR_FMT_REL,\n" +
            "MKT_RES_ATTR_VALUE,\n" +
            "MKT_RES_BATCH_REC,\n" +
            "MKT_RES_BATCH_REC_ATTR,\n" +
            "MKT_RES_CARD_EVENT,\n" +
            "MKT_RES_CARD_EVT_DETAIL,\n" +
            "MKT_RES_CARD_INST,\n" +
            "MKT_RES_CARD_INST_ATTR,\n" +
            "MKT_RES_CARD_NUM_ATTR,\n" +
            "MKT_RES_CARD_USE_REC,\n" +
            "MKT_RES_CHNG_EVT_DETAIL,\n" +
            "MKT_RES_DELIVERY,\n" +
            "MKT_RES_DELIVERY_DETAIL,\n" +
            "ACCOUNT,\n" +
            "ACCOUNT_AUTH,\n" +
            "ACCTION,\n" +
            "ACCT_BALANCE,\n" +
            "ACCT_BALANCE_LOG,\n" +
            "ACCT_CREDIT,\n" +
            "ACCT_ITEM,\n" +
            "ACCT_ITEM_ADJUST,\n" +
            "ACCT_ITEM_ADJUST_LOG,\n" +
            "ACCT_ITEM_CLASS,\n" +
            "ACCT_ITEM_GROUP,\n" +
            "ACCT_ITEM_GROUP_MEMBER,\n" +
            "ACCT_ITEM_PLUSMINUS,\n" +
            "ACCT_ITEM_SOURCE,\n" +
            "ACCT_ITEM_TOTAL_DAY,\n" +
            "ACCT_ITEM_TOTAL_MONTH,\n" +
            "ACCT_ITEM_TYPE,\n" +
            "ACCT_ITEM_UNCHARGE,\n" +
            "ACCT_ITEM_UNCHARGE_DAY,\n" +
            "ACCT_RELATIONSHIP,\n" +
            "ACCUMULATION,\n" +
            "ACCU_ATTR_DEFINE,\n" +
            "ACCU_ATTR_VALUE_DEFINE,\n" +
            "ACCU_INIT_RULE,\n" +
            "ACCU_OBJECT_INST,\n" +
            "ACCU_PAYOUT,\n" +
            "ACCU_SOURCE,\n" +
            "ACCU_TYPE,\n" +
            "ACCU_TYPE_ATTR,\n" +
            "ACCU_TYPE_GROUP,\n" +
            "ACCU_TYPE_GROUP_MBR,\n" +
            "ACC_NBR_TYPE,\n" +
            "ACC_NUM_REL,\n" +
            "ACC_NUM_TYPE_ATTR,\n" +
            "ACC_NUM_TYPE_ATTR_VALUE,\n" +
            "ACTI_REF_OBJECT,\n" +
            "ADDRESS,\n" +
            "ADJUST_REQUEST_INFO,\n" +
            "AGGREGATE_OBJECT,\n" +
            "AGREEMENT,\n" +
            "AGREEMENT_ATTR,\n" +
            "AGREEMENT_DISPUTE,\n" +
            "AGREEMENT_ITEM,\n" +
            "AGREEMENT_PERFORM,\n" +
            "AGREEMENT_TMP,\n" +
            "AGREE_CATALOG_LOCATION,\n" +
            "AGREE_ITEM_ATTR,\n" +
            "AGREE_ITEM_OBJ,\n" +
            "AGREE_ITEM_REL,\n" +
            "AGREE_ITEM_TMP,\n" +
            "AGREE_ITEM_TMP_ATTR,\n" +
            "AGREE_ITEM_TMP_ATTR_OBJ,\n" +
            "AGREE_ITEM_TMP_GRP,\n" +
            "AGREE_OBJ_TYPE,\n" +
            "AGREE_TMP_ATTR,\n" +
            "AGREE_TMP_ITEM_DETAIL,\n" +
            "AGREE_TMP_ITEM_REL,\n" +
            "AGREE_TMP_REGION_REL,\n" +
            "ALIAS,\n" +
            "AM_TEMPLATE_2_CATEGORY_NODE,\n" +
            "APPORTION_RESULT,\n" +
            "AREA_CODE,\n" +
            "ATTR_CALC_RUL,\n" +
            "ATTR_RESTRICT_VALUE,\n" +
            "ATTR_SPEC,\n" +
            "ATTR_SPEC_REL,\n" +
            "ATTR_VALUE,\n" +
            "AUDIT_BATCH,\n" +
            "AUDIT_MEASURE_DEF,\n" +
            "AUDIT_OP_TYPE,\n" +
            "AUDIT_ORDER,\n" +
            "AUDIT_ROLE_DEF,\n" +
            "AUDIT_STEP,\n" +
            "BAD_DEBT_ACCT_ITEM,\n" +
            "BAD_DEBT_PROC_TASK,\n" +
            "BALANCE_ACCT_ITEM_PAYED,\n" +
            "BALANCE_PAYOUT,\n" +
            "BALANCE_PRESENT_COND,\n" +
            "BALANCE_PRESENT_RULE,\n" +
            "BALANCE_REL,\n" +
            "BALANCE_RESERVE_DETAIL,\n" +
            "BALANCE_SHARE_RULE,\n" +
            "BALANCE_SHARE_RULE_TYPE,\n" +
            "BALANCE_SOURCE_TYPE,\n" +
            "BALANCE_SPECIAL_PAYMENT_DESC,\n" +
            "BALANCE_TYPE,\n" +
            "BALANCE_TYPE_PARAM,\n" +
            "BANK,\n" +
            "BANK_AGENT_ACCT_ITEM,\n" +
            "BANK_AGENT_FILE_FORMAT,\n" +
            "BANK_AGENT_SEND,\n" +
            "BANK_BRANCH,\n" +
            "BANK_FORMAT,\n" +
            "BANK_ITEM_TYPE,\n" +
            "BANK_ITEM_TYPE_REL,\n" +
            "BATCH_ACTION_CFG,\n" +
            "BATCH_MONITOR_CONDITION,\n" +
            "BATCH_PRIOR_CFG,\n" +
            "BATCH_TASK,\n" +
            "BATCH_TASK_DETAIL,\n" +
            "BATCH_TEMPLATE,\n" +
            "BILLING_CYCLE_TYPE,\n" +
            "BILLING_REGION,\n" +
            "BILL_ACCT_ITEM,\n" +
            "BILL_CUST_ACCT_ITEM_GROUP,\n" +
            "BILL_CUST_ACCT_ITEM_GROUP_REL,\n" +
            "BILL_CUST_ACCT_ITEM_MEMBER,\n" +
            "BILL_CUST_PROD_SPEC_MERGE,\n" +
            "BILL_FORMAT,\n" +
            "BILL_FORMAT_BLOCK,\n" +
            "BILL_FORMAT_BLOCK_GRAPHIC,\n" +
            "BILL_FORMAT_BLOCK_HISTOGRAM,\n" +
            "BILL_FORMAT_BLOCK_TABLE,\n" +
            "BILL_FORMAT_BLOCK_TAB_CELL,\n" +
            "BILL_FORMAT_BLOCK_TAB_COL,\n" +
            "BILL_FORMAT_BLOCK_TAB_ROW,\n" +
            "BILL_FORMAT_CUSTOMIZE_DTL,\n" +
            "BILL_FORMAT_ITEM,\n" +
            "BILL_FORMAT_SELECTOR,\n" +
            "BILL_FORMAT_SURFACE,\n" +
            "BILL_ITEM,\n" +
            "BILL_ITEM_OFFER_REL,\n" +
            "BILL_OFFER_TYPE,\n" +
            "BILL_OFFER_TYPE_OFFER_REL,\n" +
            "BILL_PUSH_LOG,\n" +
            "BILL_PUSH_SUB_LOG,\n" +
            "BILL_RECORD,\n" +
            "BILL_REMARK,\n" +
            "BILL_TEMPLET,\n" +
            "BILL_TEMPLET_FORMAT_REL,\n" +
            "BILL_VARIABLE,\n" +
            "BORDER_ROA_REG_REL,\n" +
            "BRAND,\n" +
            "BRAND_ATTRIBUTE,\n" +
            "BRAND_ATTRIBUTE_SPEC,\n" +
            "BRAND_ATTRIBUTE_VALUE,\n" +
            "BULLETIN,\n" +
            "BULLETIN_RCV_OBJ_REL,\n" +
            "BUSINESS_RECORD,\n" +
            "BUSINESS_REQ_INFO,\n" +
            "BUSINESS_TRAIN_INFO,\n" +
            "BUSI_OBJ,\n" +
            "BUSI_OBJECT_ATTR_VALUE_REL,\n" +
            "BUSI_OBJ_ATTR,\n" +
            "BUSI_OBJ_ATTR_VALUE,\n" +
            "BUSI_TYPE,\n" +
            "CARD_NUM_REL,\n" +
            "CART_ITEM_ATTR,\n" +
            "CATALOG,\n" +
            "CATALOG_ITEM,\n" +
            "CELL_INFO,\n" +
            "CERT_INFO,\n" +
            "CERT_INFO_SYS_REL,\n" +
            "CHANNEL,\n" +
            "CHANNEL_ACCOUNT,\n" +
            "CHANNEL_APPLICATIONS,\n" +
            "SERVSTATE_PRICING_PARA,\n" +
            "RENT_PARA_TEMPLATE,\n" +
            "MAKET_STRATEGY,\n" +
            "AGREE_ITEM_TMP_OBJ,\n" +
            "CUSTOMER,\n" +
            "AUDIT_STEP_DEF,\n" +
            "ORD_PARTY_IND,\n" +
            "BALANCE_SOURCE,\n" +
            "BILL,\n" +
            "OFFER_CATALOG_LOCATION,\n" +
            "ORDER_ITEM_ATTR,\n" +
            "ORDER_ITEM_MODIFY,\n" +
            "ORDER_ITEM_REL,\n" +
            "ORD_ACCOUNT_AUTH,\n" +
            "ORD_CERT_INFO_SYS_REL,\n" +
            "ORD_CONTACTS_INFO_ATTR,\n" +
            "ORD_CREDIT_LIMIT,\n" +
            "ORD_CUST_ATTR,\n" +
            "ORD_CUST_CONTACT_INFO_REL,\n" +
            "ORD_GROUP_PAY_TRANS_INST,\n" +
            "ORD_MKT_RES_INST_ATTR,\n" +
            "ORD_MKT_RES_INST_STORE,\n" +
            "ORD_OFFER_INST_ASSURE,\n" +
            "ORD_OFFER_INST_ATTR,\n" +
            "ORD_OFFER_INST_FEE_ATTR,\n" +
            "ORD_OFFER_INST_FEE_INFO,\n" +
            "ORD_OFFER_INST_REL,\n" +
            "ORD_OFFER_OBJ_INST_REL,\n" +
            "ORD_OFFER_PROD_INST_REL,\n" +
            "ORD_OFFER_RES_INST_REL,\n" +
            "ORD_PARTY_ATTR,\n" +
            "ORD_PARTY_CERT,\n" +
            "ORD_PARTY_ORG,\n" +
            "ORD_PARTY_REL,\n" +
            "ORD_PARTY_ROLE,\n" +
            "ORD_PAYMENT_PLAN,\n" +
            "ORD_PROD_INST_ACC_NUM,\n" +
            "ORD_PROD_INST_ATTR,\n" +
            "ORD_PROD_INST_CONTACT,\n" +
            "ORD_PROD_INST_REL,\n" +
            "ORD_PROD_INST_STATE,\n" +
            "ORD_PROD_RES_INST_REL,\n" +
            "ORD_SERVICE_REQMT_IND,\n" +
            "ORD_SERV_ACCT_REL,\n" +
            "ORD_SERV_ACCT_REL_ATTR,\n" +
            "ORD_SPECIAL_REQMT_IND,\n" +
            "ORD_TAX_PAYER_ATTR,\n" +
            "PAYMENT,\n" +
            "PAYMENT_PLAN,\n" +
            "Rent_Para_Template,\n" +
            "SALE_CUST_ATTR,\n" +
            "SALE_OFFER_INST_ATTR,\n" +
            "SALE_OFFER_INST_REL,\n" +
            "SALE_OFFER_OBJ_INST_REL,\n" +
            "SALE_OFFER_PROD_INST_REL,\n" +
            "SALE_OFFER_RES_INST_REL,\n" +
            "SALE_ORDER_ITEM_REL,\n" +
            "SALE_PROD_INST_ATTR,\n" +
            "SALE_PROD_INST_REL,\n" +
            "SALE_PROD_RES_INST_REL,\n";

   static String s2="ACCOUNT\n" +
            "ACCOUNT_AUTH\n" +
            "ACCTION\n" +
            "ACCT_BALANCE\n" +
            "ACCT_BALANCE_LOG\n" +
            "ACCT_CREDIT\n" +
            "ACCT_ITEM\n" +
            "ACCT_ITEM_ADJUST\n" +
            "ACCT_ITEM_ADJUST_LOG\n" +
            "ACCT_ITEM_CLASS\n" +
            "ACCT_ITEM_GROUP\n" +
            "ACCT_ITEM_GROUP_MEMBER\n" +
            "ACCT_ITEM_PLUSMINUS\n" +
            "ACCT_ITEM_SOURCE\n" +
            "ACCT_ITEM_TOTAL_DAY\n" +
            "ACCT_ITEM_TOTAL_MONTH\n" +
            "ACCT_ITEM_TYPE\n" +
            "ACCT_ITEM_UNCHARGE\n" +
            "ACCT_ITEM_UNCHARGE_DAY\n" +
            "ACCT_RELATIONSHIP\n" +
            "ACCUMULATION\n" +
            "ACCU_ATTR_DEFINE\n" +
            "ACCU_ATTR_VALUE_DEFINE\n" +
            "ACCU_INIT_RULE\n" +
            "ACCU_OBJECT_INST\n" +
            "ACCU_PAYOUT\n" +
            "ACCU_SOURCE\n" +
            "ACCU_TYPE\n" +
            "ACCU_TYPE_ATTR\n" +
            "ACCU_TYPE_GROUP\n" +
            "ACCU_TYPE_GROUP_MBR\n" +
            "ACC_NBR_TYPE\n" +
            "ACC_NUM_REL\n" +
            "ACC_NUM_TYPE_ATTR\n" +
            "ACC_NUM_TYPE_ATTR_VALUE\n" +
            "ACTI_REF_OBJECT\n" +
            "ADDRESS\n" +
            "ADJUST_REQUEST_INFO\n" +
            "AGGREGATE_OBJECT\n" +
            "AGREEMENT\n" +
            "AGREEMENT_ATTR\n" +
            "AGREEMENT_DISPUTE\n" +
            "AGREEMENT_ITEM\n" +
            "AGREEMENT_PERFORM\n" +
            "AGREEMENT_TMP\n" +
            "AGREE_CATALOG_LOCATION\n" +
            "AGREE_ITEM_ATTR\n" +
            "AGREE_ITEM_OBJ\n" +
            "AGREE_ITEM_REL\n" +
            "AGREE_ITEM_TMP\n" +
            "AGREE_ITEM_TMP_ATTR\n" +
            "AGREE_ITEM_TMP_ATTR_OBJ\n" +
            "AGREE_ITEM_TMP_GRP\n" +
            "AGREE_ITEM_TMP_OBJ\n" +
            "AGREE_OBJ_TYPE\n" +
            "AGREE_TMP_ATTR\n" +
            "AGREE_TMP_ITEM_DETAIL\n" +
            "AGREE_TMP_ITEM_REL\n" +
            "AGREE_TMP_REGION_REL\n" +
            "ALIAS\n" +
            "AM_TEMPLATE_2_CATEGORY_NODE\n" +
            "APPORTION_RESULT\n" +
            "AREA_CODE\n" +
            "ATTR_CALC_RUL\n" +
            "ATTR_RESTRICT_VALUE\n" +
            "ATTR_SPEC\n" +
            "ATTR_SPEC_REL\n" +
            "ATTR_VALUE\n" +
            "AUDIT_BATCH\n" +
            "AUDIT_MEASURE_DEF\n" +
            "AUDIT_OP_TYPE\n" +
            "AUDIT_ORDER\n" +
            "AUDIT_ROLE_DEF\n" +
            "AUDIT_STEP\n" +
            "AUDIT_STEP_DEF\n" +
            "BAD_DEBT_ACCT_ITEM\n" +
            "BAD_DEBT_PROC_TASK\n" +
            "BALANCE_ACCT_ITEM_PAYED\n" +
            "BALANCE_PAYOUT\n" +
            "BALANCE_PRESENT_COND\n" +
            "BALANCE_PRESENT_RULE\n" +
            "BALANCE_REL\n" +
            "BALANCE_RESERVE_DETAIL\n" +
            "BALANCE_SHARE_RULE\n" +
            "BALANCE_SHARE_RULE_TYPE\n" +
            "BALANCE_SOURCE\n" +
            "BALANCE_SOURCE_TYPE\n" +
            "BALANCE_SPECIAL_PAYMENT\n" +
            "BALANCE_SPECIAL_PAYMENT_DESC\n" +
            "BALANCE_TYPE\n" +
            "BALANCE_TYPE_PARAM\n" +
            "BANK\n" +
            "BANK_AGENT_ACCT_ITEM\n" +
            "BANK_AGENT_FILE_FORMAT\n" +
            "BANK_AGENT_SEND\n" +
            "BANK_BRANCH\n" +
            "BANK_FORMAT\n" +
            "BANK_ITEM_TYPE\n" +
            "BANK_ITEM_TYPE_REL\n" +
            "BATCH_ACTION_CFG\n" +
            "BATCH_MONITOR_CONDITION\n" +
            "BATCH_PRIOR_CFG\n" +
            "BATCH_TASK\n" +
            "BATCH_TASK_DETAIL\n" +
            "BATCH_TEMPLATE\n" +
            "BILL\n" +
            "BILLING_CYCLE_TYPE\n" +
            "BILLING_REGION\n" +
            "BILL_ACCT_ITEM\n" +
            "BILL_CUST_ACCT_ITEM_GROUP\n" +
            "BILL_CUST_ACCT_ITEM_GROUP_REL\n" +
            "BILL_CUST_ACCT_ITEM_MEMBER\n" +
            "BILL_CUST_PROD_SPEC_MERGE\n" +
            "BILL_FORMAT\n" +
            "BILL_FORMAT_BLOCK\n" +
            "BILL_FORMAT_BLOCK_GRAPHIC\n" +
            "BILL_FORMAT_BLOCK_HISTOGRAM\n" +
            "BILL_FORMAT_BLOCK_TABLE\n" +
            "BILL_FORMAT_BLOCK_TAB_CELL\n" +
            "BILL_FORMAT_BLOCK_TAB_COL\n" +
            "BILL_FORMAT_BLOCK_TAB_ROW\n" +
            "BILL_FORMAT_CUSTOMIZE_DTL\n" +
            "BILL_FORMAT_ITEM\n" +
            "BILL_FORMAT_SELECTOR\n" +
            "BILL_FORMAT_SURFACE\n" +
            "BILL_ITEM\n" +
            "BILL_ITEM_OFFER_REL\n" +
            "BILL_OFFER_TYPE\n" +
            "BILL_OFFER_TYPE_OFFER_REL\n" +
            "BILL_PUSH_LOG\n" +
            "BILL_PUSH_SUB_LOG\n" +
            "BILL_RECORD\n" +
            "BILL_REMARK\n" +
            "BILL_TEMPLET\n" +
            "BILL_TEMPLET_FORMAT_REL\n" +
            "BILL_VARIABLE\n" +
            "BORDER_ROA_REG_REL\n" +
            "BRAND\n" +
            "BRAND_ATTRIBUTE\n" +
            "BRAND_ATTRIBUTE_SPEC\n" +
            "BRAND_ATTRIBUTE_VALUE\n" +
            "BRAND_RELATION\n" +
            "BULLETIN\n" +
            "BULLETIN_RCV_OBJ_REL\n" +
            "BUSINESS_RECORD\n" +
            "BUSINESS_REQ_INFO\n" +
            "BUSINESS_TRAIN_INFO\n" +
            "BUSI_OBJ\n" +
            "BUSI_OBJECT_ATTR_VALUE_REL\n" +
            "BUSI_OBJ_ATTR\n" +
            "BUSI_OBJ_ATTR_VALUE\n" +
            "BUSI_TYPE\n" +
            "CARD_NUM_REL\n" +
            "CART_ITEM_ATTR\n" +
            "CATALOG\n" +
            "CATALOG_ITEM\n" +
            "CELL_INFO\n" +
            "CERT_INFO\n" +
            "CERT_INFO_SYS_REL\n" +
            "CHANNEL\n" +
            "CHANNEL\n" +
            "CHANNEL_ACCOUNT\n" +
            "CHANNEL_APPLICATIONS\n" +
            "CHANNEL_ATTR\n" +
            "CHANNEL_ATTRIBUTE\n" +
            "CHANNEL_AUTHORIZATION\n" +
            "CHANNEL_CHG_INFO\n" +
            "CHANNEL_CONTRACT\n" +
            "CHANNEL_CPN_INFO\n" +
            "CHANNEL_CPN_WORKSHEET\n" +
            "CHANNEL_KPI\n" +
            "CHANNEL_MEMBER\n" +
            "CHANNEL_MEMBER_ATTRIBUTE\n" +
            "CHANNEL_OPERATORS_RELA\n" +
            "CHANNEL_RELA\n" +
            "CHANNEL_RESOURCE\n" +
            "CHANNEL_TEAM\n" +
            "CHANNEL_TRAIN_INFO\n" +
            "CHECK_REQUEST_INFO\n" +
            "CHN_ABNL_INFO\n" +
            "CHN_ACC_AMT_ADJ_INFO\n" +
            "CHN_ACC_AMT_CHG_INFO\n" +
            "CHN_ACC_ATTR\n" +
            "CHN_ASSESS_ADJ_REC\n" +
            "CHN_ASSESS_REC\n" +
            "CHN_AUTH_OBJ\n" +
            "CHN_AUTH_STATUS_CHG_REL\n" +
            "CHN_CONTRACT_CHG\n" +
            "CHN_CORR_INTER_MODE\n" +
            "CHN_CORR_ORG_UNIT\n" +
            "CHN_EVAL_REC\n" +
            "CHN_MEM_TRAIN\n" +
            "CHN_ORG_UNIT\n" +
            "CHN_ORG_UNIT_CORR_MEM\n" +
            "CHN_ORG_UNIT_REL\n" +
            "CHN_RES_APPL\n" +
            "CLUB\n" +
            "CLUB_MEMBER\n" +
            "CLUB_MEMBER_ACTION\n" +
            "CLUB_MEMBER_LEV_SERVICE_REL\n" +
            "CLUB_MEMBER_SERVICE\n" +
            "COMM_ACCT\n" +
            "CONN_ACCOUNT\n" +
            "CONTACTS_INFO\n" +
            "CONTACTS_INFO_ATTR\n" +
            "CONTENT\n" +
            "CONTENT_ATTR\n" +
            "COUNT_LIMIT_COMP_MBR\n" +
            "COUPON\n" +
            "COUPON_INST\n" +
            "CREDIT\n" +
            "CREDIT_LIMIT\n" +
            "CREDIT_LIMIT_LOG\n" +
            "CREDIT_LOG\n" +
            "CREDIT_RSTR_RUL\n" +
            "CREDIT_RUL\n" +
            "CUSTOMER\n" +
            "CUSTOMER_ORDER\n" +
            "CUST_ASSIGN_REL\n" +
            "CUST_ATTR\n" +
            "CUST_BRAND\n" +
            "CUST_BRAND_HIS\n" +
            "CUST_CONTACT_INFO_REL\n" +
            "CUST_GROUP\n" +
            "CUST_GROUP_FEATURE\n" +
            "CUST_GROUP_FEATURE_DETAIL\n" +
            "CUST_GROUP_MEMBER\n" +
            "CUST_GROUP_REL\n" +
            "CUST_INDUSTRY_TYPE\n" +
            "CUST_KEY_INDUSTRY_REL\n" +
            "CUST_KEY_PERSON_REL\n" +
            "CUST_PROD_INST_REL\n" +
            "CUST_TREE\n" +
            "CUST_TREE_NODE\n" +
            "DATA_FORMAT\n" +
            "DATA_PRIV_RULE\n" +
            "DECISION_CHAIN\n" +
            "DECISION_CHAIN_LOG\n" +
            "DECISION_CHAIN_ROLE\n" +
            "DECISION_CHAIN_ROLE_RELA\n" +
            "DEDUCTION\n" +
            "DEPOSIT\n" +
            "DEPOSIT_PAY_RULE\n" +
            "DEPOSIT_TRADE_DETAIL\n" +
            "DEPOSIT_TRADE_DETAIL_ATTR\n" +
            "DEPOSIT_TYPE\n" +
            "DEST_EVENT_FORMAT\n" +
            "DEST_EVENT_FORMAT_ITEM\n" +
            "DEST_EVENT_TYPE\n" +
            "DEV_STAFF_INFO\n" +
            "DF_OFFER_GIFT_SET\n" +
            "DISCOUNT_CALC\n" +
            "DISCOUNT_CALC_METHOD\n" +
            "DISCOUNT_CALC_OBJECT\n" +
            "DISCOUNT_REPATITION_TYPE\n" +
            "DISCOUNT_TARGET_OBJECT\n" +
            "DISCOUNT_TIME_LIMIT\n" +
            "DOCUMENT\n" +
            "DOC_CONTENT\n" +
            "EMULATORY_PARTNER\n" +
            "EQUIP\n" +
            "EQUIP_REGION\n" +
            "EQUIP_TYPE\n" +
            "EVENT_ATTR\n" +
            "EVENT_CONTENT\n" +
            "EVENT_CONTENT_INDEX\n" +
            "EVENT_PRICING_STRATEGY\n" +
            "EXCH\n" +
            "EXCH_NUM_REL\n" +
            "EXPRESS\n" +
            "EXPRESS_TEMPLATE\n" +
            "EXPRESS_TEMPLATE_PARAM\n" +
            "EXT_ACCT\n" +
            "FIXED_PRICE\n" +
            "FORMAT_SCRIPT\n" +
            "FUNC_COMP\n" +
            "FUNC_MENU\n" +
            "GRID\n" +
            "GRID_ASSIGN_REL\n" +
            "GRID_ATTRIBUTE\n" +
            "GRID_CUST_RELA\n" +
            "GRID_GRID_UNIT_RELA\n" +
            "GRID_PROD_RELA\n" +
            "GRID_UNIT\n" +
            "GRID_UNIT_ATTRIBUTE\n" +
            "GRID_UNIT_PROD_RELA\n" +
            "GROUP_PAY_LIMIT\n" +
            "GROUP_PAY_TRANS_INST\n" +
            "GROUP_PURCHASE\n" +
            "HANDWORK_ACCT_ITEM\n" +
            "HANDWORK_ACCT_ITEM_DETAIL\n" +
            "HCODE\n" +
            "INTEGRAL_BALANCE_PAYOUT\n" +
            "INTEGRAL_BALANCE_SOURCE\n" +
            "INTEGRAL_CALC_RULE\n" +
            "INTEGRAL_CALC_RULE_REL\n" +
            "INTEGRAL_CONDITION\n" +
            "INTEGRAL_EVENT_TYPE\n" +
            "INTEGRAL_EXCH_DETAIL\n" +
            "INTEGRAL_EXCH_RULE\n" +
            "INTEGRAL_FACTOR\n" +
            "INTEGRAL_TARIFF\n" +
            "INTEGRAL_TYPE\n" +
            "INTERACTION_MODE\n" +
            "INTERVIEW_LOG\n" +
            "INTERVIEW_PLAN\n" +
            "INTERVIEW_PLAN_ATTACH\n" +
            "INTF_UNITEPAY_OPERATION_LOG\n" +
            "INVOICE\n" +
            "INVOICE_TAKE_RECORD\n" +
            "INVOICE_TYPE\n" +
            "INV_CANCEL\n" +
            "INV_DETAIL\n" +
            "INV_ISSUED_AD_DETAIL\n" +
            "INV_ISSUED_DETAIL\n" +
            "INV_ISSUED_REC\n" +
            "INV_PRINT_LOG\n" +
            "KEY_PERSON\n" +
            "KEY_PERSON_ATTR\n" +
            "KEY_PERSON_REL\n" +
            "LABEL\n" +
            "LABEL_GROUP\n" +
            "LABEL_GROUP_REL\n" +
            "LATE_FEE_ADJUST\n" +
            "LATE_FEE_ADJUSTED_REASON\n" +
            "LATE_FEE_COMPUTE_RULE\n" +
            "LATE_FEE_RATE\n" +
            "LIFE_CYCLE\n" +
            "LOCAL_HEAD\n" +
            "LOCAL_HEAD\n" +
            "LOCAL_HLR\n" +
            "MEASURE_METHOD\n" +
            "MEMBER_ACTION_RECORD\n" +
            "MEMBER_ASSESS_RECORD\n" +
            "MEMBER_CARD_GRANT_RECORD\n" +
            "MEMBER_CHANGE_RECORD\n" +
            "MEMBER_EXTENDED_ATTRIBUTE\n" +
            "MEMBER_SERVICE_CATALOG_LOC\n" +
            "MEMBER_SERVICE_RECORD\n" +
            "MEM_SERV_ACCT\n" +
            "MIN_NBR\n" +
            "MIN_NUM_REL\n" +
            "MIN_SECTION\n" +
            "MKT_RESOURCE\n" +
            "MKT_RES_ATTR\n" +
            "MKT_RES_ATTR_FMT_REL\n" +
            "MKT_RES_ATTR_VALUE\n" +
            "MKT_RES_BATCH_REC\n" +
            "MKT_RES_BATCH_REC_ATTR\n" +
            "MKT_RES_CARD_EVENT\n" +
            "MKT_RES_CARD_EVT_DETAIL\n" +
            "MKT_RES_CARD_INST\n" +
            "MKT_RES_CARD_INST_ATTR\n" +
            "MKT_RES_CARD_NUM_ATTR\n" +
            "MKT_RES_CARD_USE_REC\n" +
            "MKT_RES_CHNG_EVT_DETAIL\n" +
            "MKT_RES_DELIVERY\n" +
            "MKT_RES_DELIVERY_DETAIL\n" +
            "MKT_RES_EVENT\n" +
            "MKT_RES_EXTTYPE\n" +
            "MKT_RES_EXTTYPE_ATTR\n" +
            "MKT_RES_EXTTYPE_ATTR_VALUE\n" +
            "MKT_RES_EXT_ATTR\n" +
            "MKT_RES_GRP\n" +
            "MKT_RES_GRP_RES_REL\n" +
            "MKT_RES_INST\n" +
            "MKT_RES_INST_ATTR\n" +
            "MKT_RES_INST_STORE\n" +
            "MKT_RES_INVENTORY_DETAIL\n" +
            "MKT_RES_INV_ERR_REC\n" +
            "MKT_RES_INV_EVENT\n" +
            "MKT_RES_INV_EVT_DETAIL\n" +
            "MKT_RES_INV_INST\n" +
            "MKT_RES_INV_INST_ATTR\n" +
            "MKT_RES_INV_USE_REC\n" +
            "MKT_RES_NUM_EVENT\n" +
            "MKT_RES_NUM_EVT_DETAIL\n" +
            "MKT_RES_NUM_FMT_CFG\n" +
            "MKT_RES_NUM_INST\n" +
            "MKT_RES_NUM_PRE_USE\n" +
            "MKT_RES_NUM_USE_REC\n" +
            "MKT_RES_REGION\n" +
            "MKT_RES_REQUEST\n" +
            "MKT_RES_REQ_ATTR\n" +
            "MKT_RES_REQ_DETAIL\n" +
            "MKT_RES_REQ_ITEM\n" +
            "MKT_RES_REQ_ITEM_ATTR\n" +
            "MKT_RES_STOCK_ALARM\n" +
            "MKT_RES_STORE\n" +
            "MKT_RES_STORE_ATTR\n" +
            "MKT_RES_STORE_ORG_REL\n" +
            "MKT_RES_STORE_REL\n" +
            "MKT_RES_TYPE\n" +
            "MKT_RES_TYPE_ATTR\n" +
            "MKT_RES_TYPE_ATTR_VALUE\n" +
            "MKT_RES_TYPE_REGION\n" +
            "MKT_RES_USE_REC\n" +
            "MKT_TERMINAL_REPAIR_STATION\n" +
            "MTK_ACCT_ITEM\n" +
            "MTK_ORD_INFO\n" +
            "MTK_ORD_PAY_INFO\n" +
            "MTK_PRICING_ARRAY\n" +
            "MTK_PRICING_ATTR\n" +
            "MTK_PRICING_ENUM_PARAM\n" +
            "MTK_PRICING_PLAN\n" +
            "MTK_TAX_RATE_CONFIG\n" +
            "NUM_GENER_RUL\n" +
            "OBJECT_LABEL_REL\n" +
            "OBJ_ATTR_RSTR_RUL\n" +
            "OBJ_ATTR_RSTR_RUL_TEMPLET\n" +
            "OBJ_ATTR_RUL\n" +
            "OBJ_ATTR_VALUE_RSTR_RUL\n" +
            "OBJ_CAT_ITEM_REL\n" +
            "OBJ_COUNT_LIMIT_RUL\n" +
            "OBJ_DOC_REL\n" +
            "OBJ_REGION_REL\n" +
            "OBJ_TAB_REL\n" +
            "OCS_RESERVE_EVENT_GRP\n" +
            "OCS_RESERVE_EVENT_GRP_MEMBER\n" +
            "OCS_RESERVE_LIMIT\n" +
            "OCS_RESERVE_POLICY\n" +
            "OFFER\n" +
            "OFFER_AGREE\n" +
            "OFFER_AGREE_ATTR\n" +
            "OFFER_AGREE_FEE\n" +
            "OFFER_AGREE_OBJ\n" +
            "OFFER_APPLY_TARGET_CFG\n" +
            "OFFER_ASSURE_DEMAND\n" +
            "OFFER_ATTR\n" +
            "OFFER_ATTR_REF\n" +
            "OFFER_ATTR_RULE\n" +
            "OFFER_ATTR_VALUE\n" +
            "OFFER_CATALOG_LOCATION\n" +
            "OFFER_COMP_EFF_EXP_CFG\n" +
            "OFFER_COMP_REL_RSTR_CFG\n" +
            "OFFER_COMP_RSTR_CFG\n" +
            "OFFER_EFF_EXP_CONFIG\n" +
            "OFFER_EXP_CFG\n" +
            "OFFER_EXP_DETAIL_ATTR_CFG\n" +
            "OFFER_EXP_DETAIL_CFG\n" +
            "OFFER_EXT_ATTR\n" +
            "OFFER_GRP\n" +
            "OFFER_GRP_MEMBER\n" +
            "OFFER_GRP_RELA\n" +
            "OFFER_INST\n" +
            "OFFER_INST_ASSURE\n" +
            "OFFER_INST_ASSURE_ATTR\n" +
            "OFFER_INST_ATTR\n" +
            "OFFER_INST_FEE_ATTR\n" +
            "OFFER_INST_FEE_INFO\n" +
            "OFFER_INST_REL\n" +
            "OFFER_OBJ_INST_REL\n" +
            "OFFER_OBJ_INST_REL_ROLE\n" +
            "OFFER_OBJ_REL\n" +
            "OFFER_OBJ_REL_ROLE\n" +
            "OFFER_PACKAGE\n" +
            "OFFER_PACKAGE_RESTRICT\n" +
            "OFFER_PAYMENT_MODE\n" +
            "OFFER_PKG_ATTR\n" +
            "OFFER_PKG_ATTR_VALUE\n" +
            "OFFER_PROD_ATTR_REL_CFG\n" +
            "OFFER_PROD_INST_REL\n" +
            "OFFER_PROD_REL\n" +
            "OFFER_PROD_REL_RSTR_CFG\n" +
            "OFFER_REL\n" +
            "OFFER_REL_ROLE\n" +
            "OFFER_REL_RSTR_CFG\n" +
            "OFFER_RESTRICT\n" +
            "OFFER_RES_INST_REL\n" +
            "OFFER_RES_REL\n" +
            "OFFER_RSTR_CFG\n" +
            "OFFER_RSTR_GRP\n" +
            "OFFER_RSTR_RUL\n" +
            "OFFER_SALE_LIMIT_CFG\n" +
            "OFFER_SERVICE_REL\n" +
            "OFFER_SERV_LIMIT_CFG\n" +
            "OFFER_SERV_PRIV_CFG\n" +
            "ONE_ITEM_DISCOUNT_LOG\n" +
            "ONE_ITEM_RESULT\n" +
            "OPERATOR\n" +
            "OPERATORS\n" +
            "OPERATORS\n" +
            "OPERATORS_ATTR\n" +
            "OPERATORS_CONTACT_INFO\n" +
            "ORDER_ATTR\n" +
            "ORDER_BALANCE\n" +
            "ORDER_CONTACT_INFO\n" +
            "ORDER_HANDLER\n" +
            "ORDER_ITEM\n" +
            "ORDER_ITEM_ATTR\n" +
            "ORDER_ITEM_MODIFY\n" +
            "ORDER_ITEM_REL\n" +
            "ORDER_MODIFY\n" +
            "ORDER_SPLIT_RUL\n" +
            "ORDER_SRC\n" +
            "ORD_ACCOUNT\n" +
            "ORD_ACCOUNT_AUTH\n" +
            "ORD_ACC_NBR_ATTR\n" +
            "ORD_BILL_FORMAT_CUSTOMIZE_DTL\n" +
            "ORD_CERT_INFO\n" +
            "ORD_CERT_INFO_SYS_REL\n" +
            "ORD_COMM_ACCT\n" +
            "ORD_CONN_ACCOUNT\n" +
            "ORD_CONTACTS_INFO\n" +
            "ORD_CONTACTS_INFO_ATTR\n" +
            "ORD_CREDIT\n" +
            "ORD_CREDIT_LIMIT\n" +
            "ORD_CUSTOMER\n" +
            "ORD_CUST_ATTR\n" +
            "ORD_CUST_CONTACT_INFO_REL\n" +
            "ORD_DEV_STAFF_INFO\n" +
            "ORD_EXT_ACCT\n" +
            "ORD_GROUP_PAY_LIMIT\n" +
            "ORD_GROUP_PAY_TRANS_INST\n" +
            "ORD_MKT_RES_INST\n" +
            "ORD_MKT_RES_INST_ATTR\n" +
            "ORD_MKT_RES_INST_STORE\n" +
            "ORD_OFFER_INST\n" +
            "ORD_OFFER_INST_ASSURE\n" +
            "ORD_OFFER_INST_ATTR\n" +
            "ORD_OFFER_INST_FEE_ATTR\n" +
            "ORD_OFFER_INST_FEE_INFO\n" +
            "ORD_OFFER_INST_REL\n" +
            "ORD_OFFER_OBJ_INST_REL\n" +
            "ORD_OFFER_PROD_INST_REL\n" +
            "ORD_OFFER_RES_INST_REL\n" +
            "ORD_PARTY\n" +
            "ORD_PARTY_ATTR\n" +
            "ORD_PARTY_CERT\n" +
            "ORD_PARTY_IND\n" +
            "ORD_PARTY_ORG\n" +
            "ORD_PARTY_REL\n" +
            "ORD_PARTY_ROLE\n" +
            "ORD_PAYMENT_PLAN\n" +
            "ORD_PAY_TRANS_INST_DETAIL\n" +
            "ORD_PROD_INST\n" +
            "ORD_PROD_INST_ACC_NUM\n" +
            "ORD_PROD_INST_ATTR\n" +
            "ORD_PROD_INST_CONTACT\n" +
            "ORD_PROD_INST_REL\n" +
            "ORD_PROD_INST_STATE\n" +
            "ORD_PROD_RES_INST_REL\n" +
            "ORD_ROUTE_INFO\n" +
            "ORD_SERVICE_GRADE\n" +
            "ORD_SERVICE_REQMT_IND\n" +
            "ORD_SERV_ACCT_REL\n" +
            "ORD_SERV_ACCT_REL_ATTR\n" +
            "ORD_SPECIAL_LIST\n" +
            "ORD_SPECIAL_REQMT_IND\n" +
            "ORD_TAX_PAYER\n" +
            "ORD_TAX_PAYER_ATTR\n" +
            "ORD_TEMP_CREDIT_LIMIT\n" +
            "ORGANIZATION\n" +
            "ORG_ATTR\n" +
            "ORG_POST_REL\n" +
            "ORG_REL\n" +
            "OWNER\n" +
            "PACKAGE_OBJ_REL\n" +
            "PARAM_CONFIG\n" +
            "PARTNER\n" +
            "PARTNER_ABNORMAL\n" +
            "PARTNER_ACCOUNT\n" +
            "PARTNER_ACCT_ITEM\n" +
            "PARTNER_ATTRIBUTE\n" +
            "PARTNER_COMPLAIN_INFO\n" +
            "PARTNER_DOCUMENT\n" +
            "PARTNER_EVAL_ADJ\n" +
            "PARTNER_EVAL_ASSESS_INFO\n" +
            "PARTNER_STATUS_CHNG_REC\n" +
            "PARTY\n" +
            "PARTY_ATTR\n" +
            "PARTY_CERT\n" +
            "PARTY_CHECK_LOG\n" +
            "PARTY_IND\n" +
            "PARTY_ORG\n" +
            "PARTY_REL\n" +
            "PARTY_ROLE\n" +
            "PAYMENT\n" +
            "PAYMENT_METHOD\n" +
            "PAYMENT_PLAN\n" +
            "PAYMENT_RSTR_RUL\n" +
            "PAYMENT_RULE\n" +
            "PAY_NOTICE\n" +
            "PAY_STRATEGY\n" +
            "PAY_TRANS_INST_DETAIL\n" +
            "PLAT_INFO\n" +
            "PLCA_ACCUM_EXPRESS\n" +
            "PLCA_ACCUM_TRANSFORM_LIMIT\n" +
            "PLCA_ACCUM_TRANSFORM_RULE\n" +
            "PLCA_ACTION\n" +
            "PLCA_CONDITION\n" +
            "PLCA_EVENT_TYPE\n" +
            "PLCA_OPERATOR\n" +
            "PLCA_REF_VALUE\n" +
            "PLCA_REF_VALUE_SET\n" +
            "PLCA_SECTION\n" +
            "PLCA_SECTION_ACTION_REL\n" +
            "PLCA_STRATEGY\n" +
            "PLCA_STRATEGY_GROUP\n" +
            "PLCA_STRATEGY_OBJECT\n" +
            "PLCA_TIME_PERIOD_DEFINE\n" +
            "POLITICAL_LOCATION\n" +
            "POSITION\n" +
            "PRICING_COMBINE\n" +
            "PRICING_COMBINE_REL\n" +
            "PRICING_ENUM_PARAM\n" +
            "PRICING_OBJECT\n" +
            "PRICING_PARAM_DEFINE\n" +
            "PRICING_PLAN\n" +
            "PRICING_PLAN_REL\n" +
            "PRICING_REF_OBJECT\n" +
            "PRICING_REF_VALUE\n" +
            "PRICING_RULE\n" +
            "PRICING_SECTION\n" +
            "PRICING_SECTION_REL\n" +
            "PRICING_SECTION_TYPE\n" +
            "PRIVILEGE\n" +
            "PRIV_DATA_REL\n" +
            "PRIV_FUNC_REL\n" +
            "PRIV_GRANT\n" +
            "PRODUCT\n" +
            "PRODUCT_PROVIDER\n" +
            "PRODUCT_USAGE_EVENT_TYPE\n" +
            "PROD_ACCT_ITEM_TYPE_REL\n" +
            "PROD_ATTR\n" +
            "PROD_ATTR_VALUE\n" +
            "PROD_ATTR_VALUE_RESTRICT\n" +
            "PROD_CATALOG_LOCATION\n" +
            "PROD_INST\n" +
            "PROD_INST_ACC_NBR_ATTR\n" +
            "PROD_INST_ACC_NBR_REL\n" +
            "PROD_INST_ACC_NUM\n" +
            "PROD_INST_ASSIGN_REL\n" +
            "PROD_INST_ATTR\n" +
            "PROD_INST_ATTR_REL\n" +
            "PROD_INST_CONTACT\n" +
            "PROD_INST_HIS\n" +
            "PROD_INST_REL\n" +
            "PROD_INST_REL_ROLE\n" +
            "PROD_INST_STATE\n" +
            "PROD_NUM_TYPE_PLAT_REL\n" +
            "PROD_NUM_TYPE_REL\n" +
            "PROD_OFFER_BALANCE_REL\n" +
            "PROD_OFFER_INST_PARTY\n" +
            "PROD_OFFER_INST_REL_ROLE\n" +
            "PROD_PARTNER_REL\n" +
            "PROD_REGION_REL\n" +
            "PROD_REL\n" +
            "PROD_REL_EFF_EXP_CFG\n" +
            "PROD_REL_ROLE\n" +
            "PROD_REL_RSTR_CFG\n" +
            "PROD_REL_SERV_LINK_RUL\n" +
            "PROD_RES_INST_REL\n" +
            "PROD_RES_REL\n" +
            "PROD_SERVICE_OFFER_REL\n" +
            "PROD_SERV_REL_RSTR_CFG\n" +
            "PROD_STATUS_SERV_RSTR_CFG\n" +
            "PROMOTIONAL_ACTIVITY\n" +
            "PROMOTIONAL_ACTIVITY_RELA\n" +
            "PROMOTIONAL_ACTIVITY_TARIFF\n" +
            "PROMOTIONAL_ACT_TARIFF_RULE\n" +
            "PROM_ACTI_MTK_RELA\n" +
            "PROM_ACTI_TARIFF_RELA\n" +
            "RATABLE_CYCLE\n" +
            "RATABLE_CYCLE\n" +
            "RATABLE_CYCLE_TYPE\n" +
            "RATABLE_RESOURCE_ACCUMULATOR\n" +
            "REASON_TYPE\n" +
            "REBATE\n" +
            "RECEIPT_TAX_INVOICE\n" +
            "RECEIPT_TAX_INV_ITEM\n" +
            "REFUND_DETAIL\n" +
            "REFUND_DETAIL_ITEM\n" +
            "REGION_GRID_RELATION\n" +
            "REGION_LOCATION_REL\n" +
            "REL_SERV_LINK_RUL\n" +
            "REL_SPEC\n" +
            "REL_SPEC_ATTR\n" +
            "REPAIR_RANGE\n" +
            "REWARD_ADJ_INFO\n" +
            "REWARD_APRV_INFO\n" +
            "REWARD_INFO\n" +
            "REWARD_PAY_INFO\n" +
            "ROUTE_INFO\n" +
            "SALE_ACCOUNT\n" +
            "SALE_CUST\n" +
            "SALE_CUST_ATTR\n" +
            "SALE_HANDLER\n" +
            "SALE_ITEM\n" +
            "SALE_MKT_RES_INST\n" +
            "SALE_OFFER_INST\n" +
            "SALE_OFFER_INST_ATTR\n" +
            "SALE_OFFER_INST_REL\n" +
            "SALE_OFFER_OBJ_INST_REL\n" +
            "SALE_OFFER_PROD_INST_REL\n" +
            "SALE_OFFER_RES_INST_REL\n" +
            "SALE_ORDER\n" +
            "SALE_ORDER_ITEM_ATTR\n" +
            "SALE_ORDER_ITEM_REL\n" +
            "SALE_PROD_INST\n" +
            "SALE_PROD_INST_ATTR\n" +
            "SALE_PROD_INST_REL\n" +
            "SALE_PROD_RES_INST_REL\n" +
            "SERVICE_ABILITY\n" +
            "SERVICE_GRADE\n" +
            "SERVICE_GRADE_LOG\n" +
            "SERVICE_OFFER\n" +
            "SERVICE_REQMT_GEN\n" +
            "SERVICE_REQMT_IND\n" +
            "SERV_ACCT_REL\n" +
            "SERV_ACCT_REL_ATTR\n" +
            "SERV_ACCU_USE_INFO\n" +
            "SERV_AUTH\n" +
            "SERV_RSTR_RUL\n" +
            "SETTLE_RESULT_DETAIL_INFO\n" +
            "SETTLE_RESULT_INFO\n" +
            "SHOPPING_CART\n" +
            "SHOPPING_CART_ITEM\n" +
            "SOURCE_EVENT\n" +
            "SOURCE_EVENT_FORMAT\n" +
            "SOURCE_EVENT_FORMAT_ITEM\n" +
            "SOURCE_EVENT_FORMAT_NORMAL\n" +
            "SOURCE_EVENT_FORMAT_OTHER\n" +
            "SOURCE_EVENT_FORMAT_SEGMENT\n" +
            "SOURCE_EVENT_TYPE\n" +
            "SPECIAL_HEAD\n" +
            "SPECIAL_LIST\n" +
            "SPECIAL_REQMT_GEN\n" +
            "SPECIAL_REQMT_IND\n" +
            "STAFF\n" +
            "STAFF_ATTR\n" +
            "STAFF_ATTR\n" +
            "STAFF_CHANNEL_RELA\n" +
            "STAFF_CONTACT_INFO\n" +
            "STAFF_OPERATORS_RELA\n" +
            "STAFF_ORG_REL\n" +
            "STAFF_POST\n" +
            "SYSTEM_POST\n" +
            "SYSTEM_POST_ROLE\n" +
            "SYSTEM_ROLES\n" +
            "SYSTEM_USER\n" +
            "SYSTEM_USER_ATTR\n" +
            "SYSTEM_USER_POST\n" +
            "SYSTEM_USER_ROLE\n" +
            "SYSUSER_COLLECTION\n" +
            "SYSUSER_LOGIN_LIMIT\n" +
            "SYS_COLUMN\n" +
            "SYS_DOMAIN\n" +
            "SYS_TABLE\n" +
            "TARIFF\n" +
            "TARIFF_CALC_DESC\n" +
            "TARIFF_UNIT\n" +
            "TAX_INVOICE_FEE\n" +
            "TAX_INV_FEE\n" +
            "TAX_ITEM\n" +
            "TAX_PAYER\n" +
            "TAX_PAYER_ATTR\n" +
            "TAX_RATE_CONFIG\n" +
            "TEMP_CREDIT_LIMIT\n" +
            "THIRD_PARTY_CHN_INFO\n" +
            "TIME_SEGMENT\n" +
            "TRADE_RECORD\n" +
            "TRADE_TYPE\n" +
            "TRAFFIC_IDENTIFY\n" +
            "TRAFFIC_IDENTIFY_OBJ_REL\n" +
            "TRAFFIC_IDENTIFY_RULE\n" +
            "TRAFFIC_IDENTIFY_RULE_ATTR\n" +
            "TRAFFIC_IDENTIFY_RULE_ATTR_VAL\n" +
            "TRAFFIC_IDENTIFY_RULE_REL\n" +
            "UNITE_CHARGE_LOG\n" +
            "USER_INTEGRAL_RESULT\n" +
            "VALUE_ADDED_PROD\n" +
            "VALUE_ADDED_PROD_CONTENT_REL\n" +
            "VALUE_ADDED_PROD_INFO\n" +
            "VAT_INVOICE\n" +
            "VAT_INVOICE_DETAIL\n" +
            "VAT_INVOICE_DETAIL_PRN\n" +
            "VAT_INVOICE_PRN\n" +
            "VA_ADDED_PROD_SERV_ABILITY_REL\n" +
            "VA_OFFER\n" +
            "VA_OFFER_EFF_EXP_CONFIG\n" +
            "VA_OFFER_PRICE\n" +
            "VA_OFFER_PROD_REL\n" +
            "VA_OFFER_PROD_REL_ROLE\n" +
            "VA_ORDER_REL\n" +
            "VA_ORDER_REL_ATTR\n" +
            "VA_PROD_ATTR\n" +
            "VA_PROD_PLAT_REL\n" +
            "VA_PROD_REL\n" +
            "ZONE\n" +
            "ZONE_ITEM\n" +
            "ZONE_ITEM_VALUE";

    public static void main(String[] args) {
        String[] ss1 =s1.split(",\n");
        String[] ss2 =s2.split("\n");
        System.out.println(ss1.length);
        System.out.println(ss2.length);
        Map m2= new HashMap();
        for(int i=0;i<ss2.length;i++){
            m2.put(ss2[i],ss2[i]);
        }
        System.out.println(m2.size());
        for (int i = 0; i < ss1.length; i++) {
            if(!m2.containsKey(ss1[i])){
                System.out.println(ss1[i]);
            }
        }
    }
}
