CREATE OR REPLACE FUNCTION F_CONNECT
(
		V_TABLE  VARCHAR,
		V_SELECT VARCHAR,
		V_SOURID VARCHAR,
		V_DESTID VARCHAR,
		V_START  VARCHAR,
    V_LEVEL  VARCHAR
) RETURN table_SPLIT
		PIPELINED AS
		v_row  table_SPLIT_row;
		V_SQL  VARCHAR(8000);
		CONCUR SYS_REFCURSOR;
		V_TEMP VARCHAR(800);
BEGIN
		V_SQL := ' SELECT ' || V_SELECT || ' AS DES,LEVEL AS JBID FROM ' || V_TABLE ||
						 ' CONNECT BY PRIOR ' || V_SOURID || '=' || V_DESTID || ' ';
		IF V_START IS NOT NULL THEN
				V_SQL := V_SQL || ' START WITH ' || REPLACE(REPLACE(V_START,'{','('),'}',')');
		END IF;
    V_SQL :='SELECT DES FROM (' || V_SQL || ' ) A ';
    IF NVL(V_LEVEL,'0')!='0' THEN
       V_SQL := V_SQL || ' WHERE JBID<=' || V_LEVEL ;
    END IF;
		OPEN CONCUR FOR V_SQL;
		FETCH CONCUR
				INTO V_TEMP;
		WHILE CONCUR%FOUND LOOP
				v_row := table_SPLIT_row(V_TEMP);
				pipe row(v_row);
				FETCH CONCUR
						INTO V_TEMP;
		END LOOP;
		CLOSE CONCUR;
END;






