package com.vjsp.entity;

public class Bonus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BONUS.ENAME
     *
     * @mbg.generated
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BONUS.JOB
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BONUS.SAL
     *
     * @mbg.generated
     */
    private Short sal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BONUS.COMM
     *
     * @mbg.generated
     */
    private Short comm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BONUS.ENAME
     *
     * @return the value of BONUS.ENAME
     *
     * @mbg.generated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BONUS.ENAME
     *
     * @param ename the value for BONUS.ENAME
     *
     * @mbg.generated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BONUS.JOB
     *
     * @return the value of BONUS.JOB
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BONUS.JOB
     *
     * @param job the value for BONUS.JOB
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BONUS.SAL
     *
     * @return the value of BONUS.SAL
     *
     * @mbg.generated
     */
    public Short getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BONUS.SAL
     *
     * @param sal the value for BONUS.SAL
     *
     * @mbg.generated
     */
    public void setSal(Short sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BONUS.COMM
     *
     * @return the value of BONUS.COMM
     *
     * @mbg.generated
     */
    public Short getComm() {
        return comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BONUS.COMM
     *
     * @param comm the value for BONUS.COMM
     *
     * @mbg.generated
     */
    public void setComm(Short comm) {
        this.comm = comm;
    }
}