package com.vjsp.entity;

public class Salgrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALGRADE.GRADE
     *
     * @mbg.generated
     */
    private Short grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALGRADE.LOSAL
     *
     * @mbg.generated
     */
    private Short losal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALGRADE.HISAL
     *
     * @mbg.generated
     */
    private Short hisal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALGRADE.GRADE
     *
     * @return the value of SALGRADE.GRADE
     *
     * @mbg.generated
     */
    public Short getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALGRADE.GRADE
     *
     * @param grade the value for SALGRADE.GRADE
     *
     * @mbg.generated
     */
    public void setGrade(Short grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALGRADE.LOSAL
     *
     * @return the value of SALGRADE.LOSAL
     *
     * @mbg.generated
     */
    public Short getLosal() {
        return losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALGRADE.LOSAL
     *
     * @param losal the value for SALGRADE.LOSAL
     *
     * @mbg.generated
     */
    public void setLosal(Short losal) {
        this.losal = losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALGRADE.HISAL
     *
     * @return the value of SALGRADE.HISAL
     *
     * @mbg.generated
     */
    public Short getHisal() {
        return hisal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALGRADE.HISAL
     *
     * @param hisal the value for SALGRADE.HISAL
     *
     * @mbg.generated
     */
    public void setHisal(Short hisal) {
        this.hisal = hisal;
    }
}