package cn.com.jldata.search.spmsearch.domain;

import java.util.Date;

public class SpHelpFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.file_id
     *
     * @mbg.generated
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.file_title
     *
     * @mbg.generated
     */
    private String fileTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.file_url
     *
     * @mbg.generated
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.file_description
     *
     * @mbg.generated
     */
    private String fileDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.file_type
     *
     * @mbg.generated
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.file_extension_name
     *
     * @mbg.generated
     */
    private String fileExtensionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_help_file.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.file_id
     *
     * @return the value of sp_help_file.file_id
     *
     * @mbg.generated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.file_id
     *
     * @param fileId the value for sp_help_file.file_id
     *
     * @mbg.generated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.file_title
     *
     * @return the value of sp_help_file.file_title
     *
     * @mbg.generated
     */
    public String getFileTitle() {
        return fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.file_title
     *
     * @param fileTitle the value for sp_help_file.file_title
     *
     * @mbg.generated
     */
    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle == null ? null : fileTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.file_url
     *
     * @return the value of sp_help_file.file_url
     *
     * @mbg.generated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.file_url
     *
     * @param fileUrl the value for sp_help_file.file_url
     *
     * @mbg.generated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.file_description
     *
     * @return the value of sp_help_file.file_description
     *
     * @mbg.generated
     */
    public String getFileDescription() {
        return fileDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.file_description
     *
     * @param fileDescription the value for sp_help_file.file_description
     *
     * @mbg.generated
     */
    public void setFileDescription(String fileDescription) {
        this.fileDescription = fileDescription == null ? null : fileDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.file_type
     *
     * @return the value of sp_help_file.file_type
     *
     * @mbg.generated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.file_type
     *
     * @param fileType the value for sp_help_file.file_type
     *
     * @mbg.generated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.file_extension_name
     *
     * @return the value of sp_help_file.file_extension_name
     *
     * @mbg.generated
     */
    public String getFileExtensionName() {
        return fileExtensionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.file_extension_name
     *
     * @param fileExtensionName the value for sp_help_file.file_extension_name
     *
     * @mbg.generated
     */
    public void setFileExtensionName(String fileExtensionName) {
        this.fileExtensionName = fileExtensionName == null ? null : fileExtensionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.create_date
     *
     * @return the value of sp_help_file.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.create_date
     *
     * @param createDate the value for sp_help_file.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.create_by
     *
     * @return the value of sp_help_file.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.create_by
     *
     * @param createBy the value for sp_help_file.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.update_date
     *
     * @return the value of sp_help_file.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.update_date
     *
     * @param updateDate the value for sp_help_file.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.update_by
     *
     * @return the value of sp_help_file.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.update_by
     *
     * @param updateBy the value for sp_help_file.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_help_file.del_flag
     *
     * @return the value of sp_help_file.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_help_file.del_flag
     *
     * @param delFlag the value for sp_help_file.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}