package com.vjsp.domain;

import java.util.Date;

public class City extends CityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.CDATE
     *
     * @mbg.generated
     */
    private Date cdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.CDATE
     *
     * @return the value of CITY.CDATE
     *
     * @mbg.generated
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.CDATE
     *
     * @param cdate the value for CITY.CDATE
     *
     * @mbg.generated
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }
}