package com.ljl.study.mapper;

import com.ljl.study.entity.Salgrade;

public interface SalgradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALGRADE
     *
     * @mbg.generated
     */
    int insert(Salgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALGRADE
     *
     * @mbg.generated
     */
    int insertSelective(Salgrade record);
}