package com.ljl.dao;

import com.ljl.entity.Sysuser;

public interface SysuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSUSER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSUSER
     *
     * @mbg.generated
     */
    int insert(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSUSER
     *
     * @mbg.generated
     */
    int insertSelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSUSER
     *
     * @mbg.generated
     */
    Sysuser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSUSER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSUSER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sysuser record);
}